version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: php:8.1.4-apache
        environment:
          APP_ENV: test
    steps:
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git zip unzip
      - run:
          name: Install PHP extensions
          command: docker-php-ext-install pdo
      - checkout
      - run:
          name: Install Composer
          command: ./.circleci/install_composer.sh
      - run:
          name: Display PHP information
          command: ./.circleci/php_info.sh
        - run:
          name: Install project dependencies
          command: ./.circleci/install_deps.sh
      - run:
          name: Run CS tests
          command: ./.circleci/php_lint.sh
      - run:
          name: Run Unit tests
          command: ./.circleci/php_lint.sh
